name: "Kalzit"
version: "0.6.0"
description: "Kalzit - A platform for creating user- and privacy-focused web applications in an easy way."
information: |
    Kalzit - A platform for creating user- and privacy-focused web applications in an easy way.

authors:
    - NetLamp-Y