name: "Kalzit"
version: "0.7.0"
description: "Kalzit - A platform for creating user- and privacy-focused web applications in an easy way."
information: |
    Kalzit - A platform for creating user- and privacy-focused web applications in an easy way.

authors:
    - NetLamp-Y

products:
    - "./": "/usr/share/kalzit-root"

links:
    - /usr/share/kalzit-root/kalzit: "/usr/local/bin/kalzit"